import type {Action,Creation,Game,Category,NPC} from './types';
import {arts,backgrounds,events,factions,locations,npcNames,principles,realms,talents,talentInfo,units} from '../data/world';
export const age=(s:Game)=>Math.floor((s.day-s.born)/360);
export const date=(day:number)=>`Year ${1+Math.floor(day/360)} · Month ${1+Math.floor(day%360/30)} · Day ${1+day%30}`;
function random(s:Game){s.rng=(Math.imul(s.rng,1664525)+1013904223)>>>0;return s.rng/4294967296;}
function log(s:Game,text:string,kind='life'){s.journal.push({day:s.day,text,kind});s.notices=[text,...s.notices].slice(0,4);}
function discover(s:Game,id:string,category:Category,fields:Record<string,string>,source:string,level='Observed',reliability='Confirmed'){
 let e=s.knowledge.find(k=>k.subjectId===id);if(!e){e={subjectId:id,category,discoveryLevel:level,reliability,source,discoveredAt:s.day,fieldsKnown:{},playerNotes:''};s.knowledge.push(e);}Object.assign(e.fieldsKnown,fields);e.source=source;e.discoveryLevel=level;e.reliability=reliability;s.notices=[`Archive updated: ${fields.Name||e.fieldsKnown.Name||id}`,...s.notices].slice(0,4);
}
function knowArt(s:Game,id:string,full=false){const a=arts.find(a=>a.id===id);if(!a)return;discover(s,id,'Martial Arts',full?{Name:a.name,Type:a.category,Origin:a.origin,Grade:a.grade,Principles:a.principles.join(', '),Techniques:a.techniques.join(', '),Drawback:a.drawback,'Qi cost':String(a.qi)}:{Name:a.name,Type:a.category},full?'Manual and instruction':'Observed practice',full?'Partially Understood':'Observed');}
function knowFaction(s:Game,id:string,full=false){const f=factions.find(f=>f.id===id);if(f)discover(s,id,'Factions',full?{Name:f.name,Type:f.type,Headquarters:f.hq,Leader:f.leader,Philosophy:f.philosophy,History:f.history,Politics:f.politics,Allies:f.ally,Rivals:f.rival}:{Name:f.name,Type:f.type,Headquarters:f.hq},full?'Faction archives':'Travellers at the gate',full?'Confirmed':'Observed');}
function meet(s:Game,n:NPC){discover(s,n.id,'Characters',{Name:n.name,Age:String(n.age),Faction:factions.find(f=>f.id===n.faction)?.name||'Independent',Position:n.role,'Last seen':locations.find(l=>l.id===n.location)?.name||n.location},'Conversation');}
function knowPlace(s:Game,id:string){const l=locations.find(l=>l.id===id);if(l)discover(s,id,'World',{Name:l.name,Description:l.description,Resources:l.resources,Danger:`${l.danger}/5`},'Travel');}
export function create(c:Creation):Game{
 const seed=[...c.seed].reduce((a,x)=>(Math.imul(a,31)+x.charCodeAt(0))>>>0,2166136261);
 const s:Game={version:1,rng:seed,day:0,born:-c.age*360,creation:c,hp:100,qi:40,stamina:100,money:c.background==='Merchant Family'?70:25,realm:0,cultivation:0,foundation:5,experience:0,insights:Object.fromEntries(principles.map(p=>[p,0])),stats:{Strength:6,Agility:6,Endurance:6,Perception:6,Intelligence:6,Willpower:6,Charisma:6,'Spiritual Awareness':6,Comprehension:6,'Martial Talent':6,Potential:8,Fortune:6,'Qi Control':5,'Meridian Quality':5,Leadership:0},reputation:0,infamy:0,faction:'none',rank:0,merit:0,unit:'',location:c.birthplace,arts:{art0:5,art1:5},inventory:{'Practice sword':1,'Healing salve':2,'Rice ration':5},knowledge:[],npcs:[],journal:[],pending:null,seen:{},combat:null,dead:false,cause:'',flags:[],mentor:null,disciples:[],created:[],world:{tension:20,war:false,season:0},notices:[],legacy:[],equipped:'Practice sword',profession:'Wanderer'};
 if(/Clan|Family Descendant/.test(c.background)){s.foundation+=5;s.money+=15;s.reputation=-3;}if(c.background==='Scholar Household')s.stats.Comprehension+=4;if(c.background==='Orphan'){s.stats.Perception+=3;s.money=12;}if(c.background==='Bandit Child'){s.stats.Agility+=3;s.infamy=8;}if(c.background==='Herbalist Family')s.inventory['Healing salve']+=3;if(c.background==='Blacksmith Family')s.inventory['Iron ore']=4;if(c.background==='Military Family')s.experience=8;if(c.background==='Peasant')s.stats.Endurance+=3;if(c.background==='Disgraced Clan'){s.stats.Willpower+=3;s.reputation=-5;}if(c.background==='Sect Servant')s.arts.art2=1;
 if(c.talent==='Weak Constitution'){s.hp=75;s.stats.Comprehension+=4;}if(c.constitution==='Iron body')s.stats.Endurance+=3;if(c.constitution==='Clear meridians')s.stats['Qi Control']+=3;if(c.personality==='Compassionate')s.stats.Charisma+=2;if(c.personality==='Resolute')s.stats.Willpower+=2;if(c.personality==='Curious')s.stats.Perception+=2;
 npcNames.forEach((name,i)=>{const f=['none','cult','hua','tang','alliance'][i%5];s.npcs.push({id:`npc${i}`,name,age:16+Math.floor(random(s)*48),faction:f,location:locations[i%locations.length].id,realm:Math.floor(random(s)*4),alive:true,trust:0,respect:0,fear:0,affection:0,gratitude:0,resentment:0,rivalry:0,role:i%5===0?'Travelling artisan':i%3===0?'Instructor':'Disciple',memory:[],injured:false});});
 const friend=s.npcs[0];friend.location=s.location;friend.trust=15;friend.memory.push('Shared a childhood meal.');meet(s,friend);knowPlace(s,s.location);knowFaction(s,'alliance');knowFaction(s,'cult');knowArt(s,'art0',true);knowArt(s,'art1',true);
 discover(s,'qi','Cultivation',{Name:'Qi and the first threshold',Understanding:'Meditate for Qi, train the body, earn combat experience, and deepen a martial principle. A breakthrough requires all four.'},'An old teacher','Confirmed');discover(s,'salve','Items',{Name:'Healing salve',Effect:'Restores 35 health. Consumes one day.',Value:'12 copper'},'Family belongings');
 log(s,`${c.name} begins a ${c.age<16?'childhood':'new life'} in ${locations.find(l=>l.id===s.location)?.name}, born to a ${c.background.toLowerCase()} household.`);return s;
}
function maxHp(s:Game){return (s.creation.talent==='Weak Constitution'?75:s.creation.talent==='Heavenly Physique'?125:100)+s.realm*15;}
function maxQi(s:Game){return 40+s.realm*25;}
function die(s:Game,cause:string){s.dead=true;s.cause=cause;s.combat=null;s.pending=null;log(s,`${s.creation.name} died at ${age(s)}: ${cause}. Their story remains.`, 'legacy');}
function advance(s:Game,days:number){for(let d=0;d<days&&!s.dead;d++){
 s.day++;if(s.day%30===0){s.world.season++;s.world.tension=Math.max(0,Math.min(100,s.world.tension+Math.floor(random(s)*15)-5));
 for(const n of s.npcs.filter(n=>n.alive)){if(random(s)<.2)n.location=locations[Math.floor(random(s)*locations.length)].id;if(random(s)<.07)n.realm=Math.min(7,n.realm+1);if(random(s)<.04){n.injured=!n.injured;}if(random(s)<.02){n.faction=['cult','alliance','hua','tang','none'][Math.floor(random(s)*5)];n.role='Wanderer';}if(random(s)<.025)n.role='Instructor';}
 const n=s.npcs[Math.floor(random(s)*s.npcs.length)];if(s.knowledge.some(k=>k.subjectId===n.id))log(s,`Word reaches you: ${n.name} ${n.injured?'is recovering from a duel':`was seen near ${locations.find(l=>l.id===n.location)?.name}`}.`,'world');
 if(s.world.tension>=65&&!s.world.war){s.world.war=true;log(s,'War at the passes: the Cult and Alliance mobilise. Prices rise and service becomes dangerous.','world');discover(s,'war','History',{Name:'War at the northern passes','Orthodox account':'Cult patrols crossed the border.','Demonic account':'Alliance levies seized winter medicine.','Confirmed evidence':'Caravans were attacked; responsibility remains disputed.'},'Conflicting dispatches','Rumoured','Conflicting');}
 if(s.world.war&&s.world.tension<35){s.world.war=false;log(s,'An uneasy truce reopens the northern roads.','world');}
 }
 if(s.day%360===0){for(const n of s.npcs){n.age++;if(n.alive&&n.age>65&&random(s)<(n.age-65)/120){n.alive=false;if(s.knowledge.some(k=>k.subjectId===n.id)){discover(s,n.id,'Characters',{Status:'Deceased'},'Obituary');log(s,`${n.name} has died. Their students keep the lamps burning.`,'world');}}}if(s.npcs.length<70){const parent=s.npcs.find(n=>n.alive&&n.age>22&&n.age<45);if(parent){s.npcs.push({...parent,id:`npc${s.npcs.length}`,name:`${parent.name.split(' ')[0]} Yul ${s.npcs.length}`,age:0,realm:0,role:'Child',trust:0,respect:0,memory:[],affection:0});}}
 if(age(s)>70+5*s.realm&&random(s)<.12+(age(s)-70-s.realm*5)/100)die(s,'old age');
 }
 }s.hp=Math.min(maxHp(s),s.hp);s.qi=Math.min(maxQi(s),s.qi);s.stamina=Math.min(100,Math.max(0,s.stamina));if(s.hp<=0&&!s.dead)die(s,'unhealed wounds');}
function eventCheck(s:Game){if(s.dead||s.combat||s.pending||random(s)>.32)return;const pool=events.filter(e=>{const i=Number(e.id.slice(5));return (s.seen[e.id]===undefined||s.day-s.seen[e.id]>360)&&(i%2===0||s.seen[`event${i-1}`]!==undefined);});if(pool.length)s.pending=pool[Math.floor(random(s)*pool.length)].id;}
function beginFight(s:Game,kind:'spar'|'danger'|'tournament',npc?:NPC){const round=Number(s.flags.find(f=>f.startsWith('round:'))?.split(':')[1]||0);const p=kind==='tournament'?10+round*4+s.realm*2:kind==='danger'?12+s.realm*3:8+s.realm*3;s.combat={name:npc?.name||(kind==='tournament'?['Jang Wol','Ryu Dan','Ma Doyun'][round]||'Finalist':kind==='danger'?'Black Wind brigand':'Travelling disciple'),hp:65+s.realm*18+(kind==='tournament'?round*15:0),max:65+s.realm*18+(kind==='tournament'?round*15:0),power:p,turn:0,observed:0,intent:'An opening strike',kind,log:['Your opponent tests the distance.'],npc:npc?.id,guard:false};}
function fight(s:Game,move:string){const c=s.combat!;const allowed=['Attack','Defend','Evade','Counter','Technique','Movement Art','Internal Art','Observe','Feint','Recover','Item','Escape'];if(!allowed.includes(move))throw Error('Unknown combat move.');if(['Technique','Movement Art','Internal Art'].includes(move)&&s.qi<8)throw Error('You need at least 8 Qi.');if(['Attack','Evade','Counter','Feint','Technique'].includes(move)&&s.stamina<7)throw Error('Recover your stamina first.');
 c.turn++;let hit=0,shield=0;const mastery=Math.max(...Object.values(s.arts),...s.created.map(a=>a.mastery),0);let base=7+s.realm*3+s.stats.Strength*.6+mastery*.15+(s.equipped==='Tempered sword'?5:0);const opening=c.observed>=(s.creation.talent==='Battle Instinct'?1:2)&&c.turn%3===0;
 if(move==='Escape'){s.stamina=Math.max(0,s.stamina-5);if(c.kind!=='danger'||random(s)<.65){log(s,'You left the bout alive. Pride can be rebuilt.','combat');s.combat=null;advance(s,1);return;}c.log.push('The brigand cuts off your retreat.');}
 if(move==='Observe'){c.observed++;s.insights.Timing++;c.log.push(c.observed===1?'Their weight falls forward on the third exchange.':'Opening discovered: counter on every third exchange.');discover(s,'opponent-form','Martial Arts',{Name:'Unidentified turning form',Type:'Movement Art',Weakness:c.observed>1?'Vulnerable on the third exchange':'???'},'Combat observation');if(c.observed>=3&&s.creation.talent==='Perfect Memory'){s.arts.art19??=1;knowArt(s,'art19',true);}}
 if(move==='Attack'){hit=base;s.stamina-=7;}if(move==='Technique'){hit=base*1.65+s.insights.Force*.2;s.qi-=8;s.stamina-=7;}
 if(move==='Counter'){hit=base*(opening?2.2:.6);shield=opening?.75:.1;s.stamina-=7;}if(move==='Defend'){shield=.75;s.stamina=Math.min(100,s.stamina+4);}if(move==='Evade'){shield=random(s)<.65+s.insights.Balance*.002?1:.2;s.stamina-=7;}
 if(move==='Movement Art'){shield=.85;hit=base*.4;s.qi-=8;}if(move==='Internal Art'){s.qi-=8;s.hp=Math.min(maxHp(s),s.hp+12);shield=.4;}
 if(move==='Feint'){hit=base*.4;c.observed++;s.stamina-=7;}if(move==='Recover'){s.stamina=Math.min(100,s.stamina+25);s.qi=Math.min(maxQi(s),s.qi+5);}if(move==='Item'){if(!s.inventory['Healing salve'])throw Error('No healing salve remains.');s.inventory['Healing salve']--;s.hp=Math.min(maxHp(s),s.hp+35);}
 hit=Math.round(hit*(.9+random(s)*.2));c.hp-=hit;if(hit)c.log.push(`${move}: ${hit} damage${opening?' through an exposed opening':''}.`);
 if(c.hp<=0){const kind=c.kind;s.experience+=s.creation.talent==='Natural Fighter'?16:8;s.reputation+=kind==='tournament'?8:2;s.money+=kind==='danger'?18:kind==='tournament'?25:0;s.insights.Force+=2;s.insights.Timing+=2;for(const id of Object.keys(s.arts))s.arts[id]=Math.min(100,s.arts[id]+(s.creation.talent==='Natural Fighter'?4:2));const n=s.npcs.find(n=>n.id===c.npc);if(n){n.respect+=8;n.rivalry+=5;n.memory.push('Defeated in a fair bout.');meet(s,n);}log(s,`Defeated ${c.name} in ${kind==='tournament'?'the Luo River tournament':'a bout'}.`,'combat');s.combat=null;advance(s,1);if(kind==='tournament'){const round=Number(s.flags.find(f=>f.startsWith('round:'))?.split(':')[1]||0)+1;s.flags=s.flags.filter(f=>!f.startsWith('round:'));if(round===3){s.flags.push(`champion:${Math.floor(s.day/360)}`);s.money+=100;s.merit+=25;log(s,'Luo River champion. Your name will be carried beyond the basin.');}else s.flags.push(`round:${round}`);}return;}
 let dmg=Math.round(c.power*(.8+random(s)*.4)*(1-shield)*(s.creation.talent==='Iron Bones'?.75:1));if(c.turn%3===0)dmg=Math.round(dmg*1.4);s.hp-=dmg;c.log.push(`Their ${c.turn%3===0?'committed lunge':'strike'} deals ${dmg} damage.`);c.intent=(c.turn+1)%3===0?'A committed lunge':'A probing strike';c.log=c.log.slice(-8);
 if(s.hp<=0){if(c.kind==='danger'){die(s,'a fatal encounter in Black Wind Valley');}else{s.hp=12;s.combat=null;s.flags=s.flags.filter(f=>!f.startsWith('round:'));log(s,'Defeated, but spared. Recovery takes two weeks.','combat');advance(s,14);}}
}
export function reduce(original:Game,a:Action):Game{const s=structuredClone(original);s.notices=[];
 if(a.type==='note'){const e=s.knowledge.find(e=>e.subjectId===a.id);if(!e)throw Error('Discover this subject first.');e.playerNotes=(a.value||'').slice(0,2000);return s;}
 if(s.dead&&a.type!=='legacy')throw Error('This life has ended. Choose an heir to continue.');
 if(a.type==='legacy'){if(!s.dead)throw Error('A successor takes over only after death.');const heir=s.npcs.find(n=>n.id===a.id&&n.alive&&n.age>=12);if(!heir)throw Error('Choose a living successor age 12 or older.');const next=create({...s.creation,name:heir.name,age:heir.age,background:'Martial Family Descendant',seed:String(s.rng)});next.day=s.day;next.born=s.day-heir.age*360;next.npcs=s.npcs;next.world=s.world;next.money=Math.floor(s.money/2);next.legacy=[...s.legacy,`${s.creation.name}, ${age(s)}, ${realms[s.realm]}. ${s.cause}.`];next.created=s.created.map(x=>({...x,mastery:5}));next.journal=[...s.journal,{day:s.day,text:`${heir.name} inherits the unfinished story.`,kind:'legacy'}];discover(next,`ancestor${s.day}`,'History',{Name:s.creation.name,Legacy:`${realms[s.realm]} · ${s.profession}`,Chronicle:s.journal.filter(j=>j.kind!=='world').map(j=>`${date(j.day)}: ${j.text}`).join('\n')},'Inherited chronicle','Confirmed');return next;}
 if(s.combat){if(a.type!=='combat')throw Error('Finish or escape the current bout first.');fight(s,a.id||'');return s;}
 if(s.pending){if(a.type!=='choice')throw Error('Resolve the current encounter first.');const e=events.find(e=>e.id===s.pending)!;const choice=e.choices[Number(a.id)];if(!choice)throw Error('Choose an available response.');if(s.money<(choice.cost||0))throw Error('You do not have enough copper.');s.money-=choice.cost||0;s.seen[e.id]=s.day;s.pending=null;const n=s.npcs.find(n=>n.alive&&n.location===s.location);if(choice.effect==='kind'){s.reputation+=3;if(n){n.trust+=8;n.gratitude+=8;n.memory.push(choice.text);meet(s,n);}s.insights.Softness+=2;}if(choice.effect==='risk'){if(random(s)<.28){s.hp-=15;log(s,'The investigation leaves you with a deep cut.');}s.insights.Perception=(s.insights.Perception||0)+2;discover(s,`rumour${e.id}`,'Rumours',{Name:e.title,Account:choice.text},'Investigation','Observed','Estimated');s.flags.push('inheritance-clue');}if(choice.effect==='study'){s.insights[principles[Number(e.id.slice(5))%principles.length]]+=3;discover(s,`evidence${e.id}`,'History',{Name:e.title,Evidence:choice.text},'Witness account','Partially Understood','Estimated');}if(choice.effect==='work'){s.money+=15;s.reputation-=2;}log(s,`${e.title}: ${choice.text}`,'event');advance(s,choice.effect==='work'?5:choice.effect==='leave'?1:3);return s;}
 const days=Math.max(1,Math.min(90,Math.floor(a.days||7)));let cost=0;let check=true;
 switch(a.type){
 case 'childhood':if(age(s)>=16)throw Error('Your childhood has ended. Choose your own path.');cost=90;s.foundation+=5;s.cultivation+=10;s.insights.Balance+=3;s.stats.Willpower+=1;s.money+=10;log(s,'A season of household work and practice passes. You grow stronger, and the world grows less familiar.');break;
 case 'rest':s.hp=Math.min(maxHp(s),s.hp+days*5);s.qi=Math.min(maxQi(s),s.qi+days*4);s.stamina=Math.min(100,s.stamina+days*8);cost=days;log(s,`Rested for ${days} days. Breath and body settle.`);break;
 case 'meditate':s.cultivation+=days*(s.creation.talent==='Exceptional Meridian Network'||s.creation.talent==='Unstable Qi'?2:1);s.qi=Math.min(maxQi(s),s.qi+days*3);s.insights.Stillness+=days*(s.creation.talent==='Qi Sensitivity'?.8:.35);s.insights.Flow+=days*.15;cost=days;log(s,`Meditated for ${days} days. Stillness deepens.`);break;
 case 'train':{if(s.stamina<15&&s.creation.talent!=='Extreme Determination')throw Error('Rest before you train again.');const art=arts.find(x=>x.id===a.id);if(!art||s.arts[art.id]===undefined)throw Error('Learn this art first.');let gain=days*(1+s.stats.Comprehension/20)/art.difficulty;if((s.creation.talent==='Sword Genius'&&art.category==='Sword Arts')||(s.creation.talent==='Saber Genius'&&art.category==='Saber Arts')||(s.creation.talent==='Late Bloomer'&&age(s)>=30))gain*=2;s.arts[art.id]=Math.min(100,s.arts[art.id]+gain);s.foundation+=days*.4;s.insights[art.principles[0]]+=days*.3;s.stamina=Math.max(0,s.stamina-Math.min(65,days*2));cost=days;log(s,`Practised ${art.name} for ${days} days. Mastery ${Math.floor(s.arts[art.id])}%.`);break;}
 case 'breakthrough':{const need=threshold(s);if(!need.ready)throw Error('Build the four foundations shown in Cultivation first.');if(s.realm>=7)throw Error('You have reached the highest realm.');const success=random(s)<Math.min(.95,.65+s.stats.Willpower*.01+(s.mentor?.length?.08:0));if(success){s.realm++;s.cultivation=0;s.hp=maxHp(s);s.qi=maxQi(s);s.stats['Qi Control']+=3;log(s,`Broke through to ${realms[s.realm]}. The world feels different.`,'milestone');discover(s,`realm${s.realm}`,'Cultivation',{Name:realms[s.realm],Understanding:s.realm>=4?'Qi extends beyond the body. Insight now matters more than repetition.':'A stronger vessel, a steadier breath. Each threshold demands experience as well as Qi.'},'Personal breakthrough','Confirmed');}else{s.hp-=s.creation.talent==='Unstable Qi'?40:20;s.cultivation=Math.floor(s.cultivation*.7);log(s,'Qi deviation interrupted the breakthrough. Recover before trying again.');}cost=14;break;}
 case 'travel':{const l=locations.find(l=>l.id===a.id);if(!l)throw Error('Unknown destination.');if(l.id===s.location)throw Error('You are already here.');cost=Math.max(2,l.days);s.location=l.id;knowPlace(s,l.id);knowFaction(s,l.faction);log(s,`Travelled to ${l.name}.`);break;}
 case 'explore':cost=3;s.money+=Math.floor(random(s)*7);{const n=s.npcs.find(n=>n.alive&&n.location===s.location&&!s.knowledge.some(k=>k.subjectId===n.id));if(n)meet(s,n);}if(s.location==='valley'&&s.flags.includes('inheritance-clue')&&!s.flags.includes('inheritance')){s.flags.push('inheritance');s.arts.art22=1;knowArt(s,'art22',true);s.insights.Flow+=12;log(s,'Behind the dry waterfall, you find the Unwritten River Scripture. Its author left no name.','milestone');}else if(s.location==='valley'&&random(s)<.4){beginFight(s,'danger');discover(s,'brigands','Threats',{Name:'Black Wind brigands',Behaviour:'Exploit tired travellers',Weakness:'Overcommit every third exchange'},'Ambush');}else{log(s,'Explored the nearby paths and listened to the people who live here.');}break;
 case 'rumour':if(s.money<3)throw Error('Listening over tea costs 3 copper.');s.money-=3;cost=2;s.flags.push('inheritance-clue');discover(s,'river-secret','Rumours',{Name:'Water beneath the stone',Account:'A wounded traveller saw writing behind a dry waterfall in Black Wind Valley.',Reliability:'Unverified'},'Merchant at the inn','Rumoured','Unknown');{const id=`art${Math.floor(random(s)*arts.length)}`;knowArt(s,id);}log(s,'Shared tea and collected a rumour.');break;
 case 'work':{const job=a.id||'Merchant';s.profession=job;const bonus=s.creation.background.includes(job)||s.creation.background.includes('Merchant')?2:1;cost=days;s.money+=days*(job==='Physician'?3:job==='Blacksmith'?4:2)*bonus;s.reputation+=job==='Physician'?2:1;s.stats.Leadership+=.5;if(job==='Physician'){s.insights.Precision+=2;s.inventory['Healing salve']=(s.inventory['Healing salve']||0)+1;}if(job==='Blacksmith'){s.inventory['Iron ore']=(s.inventory['Iron ore']||0)+1;}log(s,`Worked as a ${job.toLowerCase()} for ${days} days.`);break;}
 case 'join':{if(age(s)<16)throw Error('You must be 16 to enter a faction. Train and grow first.');if(s.faction!=='none')throw Error('Leave your current faction before applying.');const f=factions.find(f=>f.id===a.id);if(!f)throw Error('Unknown faction.');const l=locations.find(l=>l.id===s.location)!;if(l.faction!==f.id)throw Error(`Travel to ${f.hq} to apply.`);if(f.id==='hua'&&s.infamy>15)throw Error('Mount Hua will not recruit someone with this infamy.');if(f.id==='tang'&&s.money<30)throw Error('Tang sponsorship requires a 30 copper bond.');if(f.id==='tang')s.money-=30;s.faction=f.id;s.rank=0;s.merit=0;s.unit=f.id==='cult'?'Latent Demon Squads':'';s.arts[`art${f.art}`]=1;knowArt(s,`art${f.art}`,true);knowFaction(s,f.id,true);cost=7;log(s,`Joined ${f.name} as ${f.ranks[0]}.`,'milestone');break;}
 case 'leave':if(s.faction==='none')throw Error('You have no faction to leave.');log(s,`Left ${factions.find(f=>f.id===s.faction)?.name}. Old loyalties will remember.`);s.faction='none';s.rank=0;s.merit=0;s.reputation-=8;cost=3;break;
 case 'unit':if(s.faction!=='cult'||s.rank<1)throw Error('Become a Demonic Soldier to request an assignment.');if(!units.some(u=>u.name===a.id))throw Error('Unknown unit.');s.unit=a.id!;cost=3;log(s,`Assigned to ${s.unit}.`);break;
 case 'service':if(s.faction==='none')throw Error('Join a faction first.');cost=7;s.merit+=s.creation.talent==='Born Leader'?20:10;s.money+=s.unit==='Twelve Support Units'?28:14;s.foundation+=4;s.insights[units.find(u=>u.name===s.unit)?.insight||'Balance']+=3;if(s.world.war||s.unit==='Charred Dragon Unit'){s.hp-=12;s.experience+=5;}if(s.unit==='Charred Dragon Unit')knowFaction(s,'alliance',true);log(s,`Completed ${s.unit||'faction'} service${s.world.war?' amid the war':''}.`);break;
 case 'promote':if(s.faction==='none'||s.rank>=7)throw Error('No promotion is available.');if(s.merit<(s.rank+1)*25||s.realm<Math.max(0,s.rank-1))throw Error('Earn more merit and cultivation before seeking promotion.');s.merit-=(s.rank+1)*25;s.rank++;cost=7;log(s,`Promoted to ${factions.find(f=>f.id===s.faction)!.ranks[s.rank]}.`,'milestone');break;
 case 'archive':if(s.faction==='none')throw Error('Join a faction to use its archives.');knowFaction(s,s.faction,true);{const pool=arts.filter(x=>x.faction===s.faction&&s.arts[x.id]===undefined&&x.realm<=s.realm);if(!pool.length)throw Error('Master your current arts and advance to access more manuals.');const art=pool[0];s.arts[art.id]=0;knowArt(s,art.id,true);log(s,`Learned the foundations of ${art.name} from the archives.`);}cost=14;break;
 case 'ordeal':if(s.location!=='cave'||s.faction!=='cult')throw Error('Enter the Cave as a Cult disciple first.');if(s.hp<45)throw Error('Recover to 45 health before an ordeal.');s.hp-=25;s.foundation+=12;s.experience+=8;s.insights.Hardness+=5;s.merit+=12;cost=14;log(s,'Survived an ordeal in the Cave. You carried an injured disciple out with you.');break;
 case 'social':case 'mentor':case 'disciple':case 'spar':{const n=s.npcs.find(n=>n.id===a.id&&n.alive);if(!n||n.location!==s.location)throw Error('Find this person at your current location first.');if(n.age<12)throw Error('This child is too young for martial obligations.');meet(s,n);if(a.type==='spar'){beginFight(s,'spar',n);check=false;break;}if(a.type==='mentor'){if(n.trust<20||n.realm<=s.realm)throw Error('A mentor needs 20 trust and a higher cultivation than yours.');s.mentor=n.id;s.insights[principles[n.realm]]+=5;s.cultivation+=10;log(s,`${n.name} accepts you for personal instruction.`);}else if(a.type==='disciple'){if(s.realm<2||n.trust<25||n.realm>=s.realm)throw Error('Reach First Rate and build 25 trust with a weaker martial artist.');if(!s.disciples.includes(n.id))s.disciples.push(n.id);n.respect+=10;n.realm=Math.min(s.realm-1,n.realm+1);if(s.created.length)n.memory.push(`Inherited ${s.created[0].name}.`);log(s,`Taught ${n.name}${s.created.length?` your ${s.created[0].name}`:''}. Your lineage takes root.`);}else{n.trust+=6;n.affection+=3;n.respect+=2;n.memory.push(`Shared time with ${s.creation.name}.`);log(s,`Spent an afternoon with ${n.name}.`);discover(s,n.id,'Characters',{Personality:n.id.length%2?'Protective of juniors, wary of authority':'Ambitious, but honours debts',Cultivation:`Estimated ${realms[n.realm]}`,Memory:n.memory.slice(-3).join(' ')},'Personal conversation','Observed','Estimated');}cost=3;break;}
 case 'tournament':if(age(s)<16)throw Error('Tournament entrants must be at least 16.');if(s.location!=='luoyang')throw Error('Travel to Luoyang for the tournament.');if(s.flags.includes(`champion:${Math.floor(s.day/360)}`))throw Error('You won this year’s tournament. Return next year.');if(s.hp<35)throw Error('Recover before entering the tournament.');beginFight(s,'tournament');check=false;log(s,'Entered the Luo River tournament. Three victories earn the title.');break;
 case 'buy':{const price=a.id==='Healing salve'?12:a.id==='Rice ration'?3:40;if(!['Healing salve','Rice ration','Tempered sword'].includes(a.id||''))throw Error('Unknown item.');if(s.money<price)throw Error('Not enough copper.');s.money-=price;s.inventory[a.id!]=(s.inventory[a.id!]||0)+1;cost=1;discover(s,a.id!,'Items',{Name:a.id!,Value:`${price} copper`,Effect:a.id==='Tempered sword'?'Adds 5 damage when equipped':a.id==='Rice ration'?'Restores 30 stamina':'Restores 35 health'},'Market purchase');log(s,`Bought ${a.id}.`);break;}
 case 'use':if(!s.inventory[a.id||''])throw Error('You do not own this item.');if(a.id?.includes('sword')){s.equipped=a.id;cost=1;log(s,`Equipped ${a.id}.`);}else if(a.id==='Healing salve'){s.inventory[a.id]--;s.hp=Math.min(maxHp(s),s.hp+35);cost=1;log(s,'Applied healing salve.');}else if(a.id==='Rice ration'){s.inventory[a.id]--;s.stamina=Math.min(100,s.stamina+30);cost=1;log(s,'Ate a rice ration.');}else throw Error('Use iron ore at the forge.');break;
 case 'forge':if((s.inventory['Iron ore']||0)<3)throw Error('Collect 3 iron ore through blacksmith work.');s.inventory['Iron ore']-=3;s.inventory['Tempered sword']=(s.inventory['Tempered sword']||0)+1;cost=14;log(s,'Forged a tempered sword.');break;
 case 'create-art':{if(s.realm<3||s.experience<40||Object.values(s.arts).filter(m=>m>=65).length<2||s.stats.Comprehension<6)throw Error('Requires Super First Rate, 40 experience, and two arts at Master (65%).');const p=a.id||'Flow',q=a.secondary||'Force';if(p===q||!principles.includes(p)||!principles.includes(q)||(s.insights[p]||0)<15||(s.insights[q]||0)<15)throw Error('Choose two different principles with at least 15 insight each.');const name=(a.name||'Unnamed River Art').trim().slice(0,60);if(!name)throw Error('Give your art a name.');const id=`created${s.created.length}`;s.created.push({id,name,principles:[p,q],weakness:p==='Force'?'High Qi consumption':'Weak against sustained pressure',mastery:10});discover(s,id,'Martial Arts',{Name:name,Creator:s.creation.name,Principles:`${p}, ${q}`,Strength:p==='Force'?'Explosive finishing strikes':'Continuous movement',Weakness:p==='Force'?'High Qi consumption':'Weak against sustained pressure'},'Personal enlightenment','Confirmed');cost=90;log(s,`Created ${name}. A new martial tradition begins.`,'milestone');break;}
 case 'refine':{const art=s.created.find(x=>x.id===a.id);if(!art)throw Error('Unknown created art.');art.mastery=Math.min(100,art.mastery+days*.5);s.insights[art.principles[0]]+=days*.2;cost=days;log(s,`Refined ${art.name}.`);break;}
 case 'retire':cost=360;log(s,'Spent a year teaching, tending old friendships, and watching the seasons.');s.money+=60;s.hp=maxHp(s);s.stamina=100;s.disciples.forEach(id=>{const n=s.npcs.find(n=>n.id===id);if(n?.alive)n.respect+=10;});break;
 default:throw Error('That action is not available.');
 }advance(s,cost);if(check)eventCheck(s);return s;
}
export function threshold(s:Game){const qi=25*(s.realm+1)**2,body=10+s.realm*15+(s.creation.talent==='Blocked Meridian'?15:0),experience=5+s.realm*12,insight=5+s.realm*8+(s.creation.talent==='Heavenly Physique'?5:0);return {qi,body,experience,insight,ready:s.realm<7&&s.cultivation>=qi&&s.foundation>=body&&s.experience>=experience&&Math.max(...Object.values(s.insights))>=insight};}
export const mastery=(n:number)=>['Untrained','Novice','Familiar','Proficient','Expert','Master','Grandmaster','Perfected','Transcendent'][n>=100?8:n>=90?7:n>=80?6:n>=65?5:n>=45?4:n>=30?3:n>=15?2:n>0?1:0];
// UI receives this projection only. Secret world records never cross this boundary.
export function view(s:Game){return {name:s.creation.name,creation:s.creation,age:age(s),day:s.day,date:date(s.day),hp:s.hp,maxHp:maxHp(s),qi:s.qi,maxQi:maxQi(s),stamina:s.stamina,money:s.money,realm:realms[s.realm],realmIndex:s.realm,faction:factions.find(f=>f.id===s.faction)?.name||'Unaffiliated',factionId:s.faction,rank:factions.find(f=>f.id===s.faction)?.ranks[s.rank]||'Wanderer',rankIndex:s.rank,merit:s.merit,unit:s.unit,location:locations.find(l=>l.id===s.location)!,stats:s.stats,foundation:s.foundation,cultivation:s.cultivation,experience:s.experience,reputation:s.reputation,infamy:s.infamy,insights:s.insights,threshold:threshold(s),arts:Object.entries(s.arts).map(([id,m])=>({id,name:arts.find(a=>a.id===id)!.name,category:arts.find(a=>a.id===id)!.category,mastery:m,level:mastery(m),principles:arts.find(a=>a.id===id)!.principles})),knowledge:s.knowledge,npcs:s.npcs.filter(n=>s.knowledge.some(k=>k.subjectId===n.id)).map(n=>({id:n.id,name:n.name,alive:n.alive,nearby:n.location===s.location,trust:n.trust,respect:n.respect,affection:n.affection,gratitude:n.gratitude,rivalry:n.rivalry,resentment:n.resentment,fear:n.fear,memory:n.memory.slice(-3),mentor:s.mentor===n.id,disciple:s.disciples.includes(n.id)})),inventory:s.inventory,equipped:s.equipped,journal:s.journal,notices:s.notices,pending:events.find(e=>e.id===s.pending)||null,combat:s.combat?{name:s.combat.name,hp:s.combat.hp,max:s.combat.max,kind:s.combat.kind,observed:s.combat.observed,intent:s.combat.observed?s.combat.intent:'???',log:s.combat.log}:null,dead:s.dead,cause:s.cause,created:s.created,legacy:s.legacy,profession:s.profession,war:s.world.war,successors:s.dead?s.npcs.filter(n=>n.alive&&n.age>=12&&(s.disciples.includes(n.id)||s.knowledge.some(k=>k.subjectId===n.id))).map(n=>({id:n.id,name:n.name,age:n.age})):[],tournamentRound:Number(s.flags.find(f=>f.startsWith('round:'))?.split(':')[1]||0),objective:s.realm===0?'Build your foundations and attempt your first breakthrough.':s.faction==='none'?'Choose a faction—or make your own way.':'Earn trust, learn from your faction, and deepen your martial path.'};}
export const creationOptions={backgrounds,talents,talentInfo,locations:locations.map(l=>({id:l.id,name:l.name})),principles};
export const destinations=locations.map(l=>({id:l.id,name:l.name,days:Math.max(2,l.days)}));
export const recruitment=factions.map(f=>({id:f.id,name:f.name,description:f.philosophy,hq:f.hq}));
export const assignments=units;

